
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jan 13 19:40:31 CET 2019
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 22;
  public static final int CHAR = 18;
  public static final int GE = 40;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int CONTINUE = 30;
  public static final int INTERFACE = 25;
  public static final int BINOR = 46;
  public static final int FOR = 28;
  public static final int MINUS = 34;
  public static final int RPAREN = 7;
  public static final int LS = 41;
  public static final int BOOL = 19;
  public static final int COMMA = 8;
  public static final int CLASS = 23;
  public static final int BINAND = 47;
  public static final int INC = 32;
  public static final int DIV = 44;
  public static final int PLUS = 11;
  public static final int IF = 20;
  public static final int DOT = 36;
  public static final int LE = 42;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int EQUAL = 12;
  public static final int NEW = 35;
  public static final int error = 1;
  public static final int MUL = 43;
  public static final int MOD = 45;
  public static final int NUMBER = 16;
  public static final int BREAK = 29;
  public static final int IDENT = 17;
  public static final int VOID = 13;
  public static final int SAME = 37;
  public static final int LBRACE = 3;
  public static final int ELSE = 21;
  public static final int LSQUARE = 14;
  public static final int ENUM = 24;
  public static final int READ = 31;
  public static final int RSQUARE = 15;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 26;
  public static final int PROG = 2;
  public static final int DIFF = 38;
  public static final int DEC = 33;
  public static final int GT = 39;
  public static final int IMPLEMENTS = 27;
  public static final int PRINT = 9;
}

